version: "3"

services:

  mongo:
    image: mongo:4.0-rc-xenial
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /data/go-auth/mongodb:/data/db

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - /data/go-auth/redis:/data

  auth:
    build: .
    container_name: auth-service
    restart: always
    environment:
      AUTH_SERVER_PORT: "4000"
      MONGO_URI: "mongodb://mongo/auth"
      REDIS_URL: "redis://redis:6379/1"
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    volumes:
      - ./cert:/app/cert
