{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: {{ template "networkPolicy.apiVersion" . }}
metadata:
  name: "{{ template "authService.fullname" . }}"
  labels:
    app: {{ template "authService.name" . }}
    chart: {{ template "authService.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  podSelector:
    matchLabels:
      app: {{ template "authService.name" . }}
      release: "{{ .Release.Name }}"
  ingress:
    # Allow inbound connections
    - ports:
      - port: 4000
      {{- if not .Values.networkPolicy.allowExternal }}
      from:
        - podSelector:
            matchLabels:
              {{ template "authService.fullname" . }}-client: "true"
      {{- end }}
    {{- if .Values.metrics.enabled }}
    # Allow prometheus scrapes for metrics
    - ports:
      - port: 9121
    {{- end }}
{{- end }}