apiVersion: v1
kind: Service
metadata:
  name: {{ template "authService.fullname" . }}
  labels:
    app: {{ template "authService.name" . }}
    chart: {{ template "authService.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ template "authService.name" . }}
  ports:
    - port: {{ .Values.service.internalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
    {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
    {{- end }}
