#!/usr/bin/env python
import argparse
import base64
import re
import os


parser = argparse.ArgumentParser()
parser.add_argument("--infile", help="Public key file")
args = parser.parse_args()


def main():
    stream = os.popen(f"openssl rsa -pubin -in {args.infile} -text -noout")
    output = stream.read()

    mod = re.findall("Modulus(.*?)Exponent", output, flags=re.S)
    hex_string = re.sub(r"[\n\s\:]*", "", mod[0])
    byte_array = bytearray.fromhex(hex_string)
    print(base64.urlsafe_b64encode(byte_array).decode().rstrip("="))


if __name__ == "__main__":
    main()
